syntax enable
set tabstop=2
set shiftwidth=2
set hidden
set nowrap
set pumheight=10
set fileencoding=utf-8
set cmdheight=2
set splitbelow
set splitright
set t_Co=256
set conceallevel=0
set smarttab
set expandtab
set smartindent
set autoindent
set laststatus=0
set number
set background=dark
set showtabline=2
set nobackup
set nowritebackup
set updatetime=300
set timeoutlen=500
